#!/usr/bin/env bash
#
# Agent Guard init stub — generated by install.sh.
#
# This file lives at the repository root and delegates to the agent-guard-core
# package. It is the only file an AI agent needs to source to acquire a lease.
#
# Usage:
#   source {{INIT_SCRIPT_NAME}} <identity> <role>
#   source {{INIT_SCRIPT_NAME}} status
#   source {{INIT_SCRIPT_NAME}} release
#   source {{INIT_SCRIPT_NAME}} attach <branch>
#   source {{INIT_SCRIPT_NAME}} triage <prefix>

set -euo pipefail

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "❌ This script must be sourced, not executed directly." >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export AGENT_GUARD_FROM_STUB=1
export AGENT_GUARD_INIT_NAME="{{INIT_SCRIPT_NAME}}"

# Resolve a usable Python interpreter cross-platform.
AG_PYTHON="$(bash "${SCRIPT_DIR}/{{PACKAGE_ROOT}}/bin/agent-guard-python" 2>/dev/null || echo "python3")"
export AG_PYTHON

# Resolve package root from agent-guard.yaml when available.
PACKAGE_ROOT="packages/agent-guard-core"
if [[ -f "${SCRIPT_DIR}/agent-guard.yaml" ]]; then
    PACKAGE_ROOT="$(${AG_PYTHON} -c "import yaml,sys; d=yaml.safe_load(open(sys.argv[1])); print(d.get('paths',{}).get('package_root','packages/agent-guard-core'))" "${SCRIPT_DIR}/agent-guard.yaml" 2>/dev/null || echo 'packages/agent-guard-core')"
fi

AGENT_GUARD_BIN="${SCRIPT_DIR}/${PACKAGE_ROOT}/bin/agent-guard"

if [[ ! -f "${AGENT_GUARD_BIN}" ]]; then
    echo "❌ agent-guard-core not found at ${AGENT_GUARD_BIN}" >&2
    return 1 2>/dev/null || exit 1
fi

# Normalize legacy flag-style commands to agent-guard subcommands.
_NORMALIZED_ARGS=("$@")
if [[ ${#_NORMALIZED_ARGS[@]} -gt 0 ]]; then
    case "${_NORMALIZED_ARGS[0]}" in
        --status) _NORMALIZED_ARGS[0]="status" ;;
        --release) _NORMALIZED_ARGS[0]="release" ;;
        --attach) _NORMALIZED_ARGS[0]="attach" ;;
        --triage) _NORMALIZED_ARGS[0]="triage" ;;
    esac
fi

source "${AGENT_GUARD_BIN}" "${_NORMALIZED_ARGS[@]}"
